const app=document.getElementById('app');
let reports=JSON.parse(localStorage.getItem('campusReports')||'[]');
let users=JSON.parse(localStorage.getItem('campusUsers')||'[]');

function save(){localStorage.setItem('campusReports',JSON.stringify(reports));localStorage.setItem('campusUsers',JSON.stringify(users));}
function home(){
app.innerHTML=`<div class="auth screen"><section class="brand-panel"><div class="logo">🛡️ CAMPUS SHIELD</div><div class="shield">🛡️</div><h1>Campus Security Alert System</h1><p>Report security incidents quickly, identify exactly where they happened, and help campus security respond faster.</p></section><section class="auth-panel"><div class="box"><h2>Welcome</h2><p class="muted">Choose how you want to continue.</p><div class="role-grid"><button class="role" onclick="showUserLogin()">👤<b>User</b><span>Students & lodge residents</span></button><button class="role" onclick="showAdminLogin()">🛡️<b>Admin</b><span>Campus security personnel</span></button></div></div></section></div>`;
}
function showUserLogin(){
app.innerHTML=`<div class="auth screen"><section class="brand-panel"><div class="logo">🛡️ CAMPUS SHIELD</div><h1>User Portal</h1><p>Sign in to report incidents and receive campus security alerts.</p></section><section class="auth-panel"><div class="box"><h2>User Login</h2><p class="muted">Access your security dashboard.</p><form class="form" onsubmit="userLogin(event)"><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" required><button class="btn primary">Sign in</button></form><button class="link" onclick="showRegister()">Create a new student account</button><br><button class="link" onclick="home()">← Back</button></div></section></div>`;
}
function showRegister(){
app.innerHTML=`<div class="auth screen"><section class="brand-panel"><div class="logo">🛡️ CAMPUS SHIELD</div><h1>Create your verified account</h1><p>Your campus, lodge and location details help security identify exactly where an alert originated.</p></section><section class="auth-panel"><div class="box"><h2>Student Registration</h2><p class="muted">Enter your details.</p><form class="form" onsubmit="register(event)"><label>Full name</label><input id="name" required><label>Student ID</label><input id="studentId" required><label>Phone number</label><input id="phone" required><label>Email</label><input id="email" type="email" required><label>Campus</label><input id="campus" placeholder="e.g. FULafia" required><label>Lodge / Compound</label><input id="lodge" required><label>Block / Building</label><input id="block" required><label>Room / House number</label><input id="room" required><label>Password</label><input id="password" type="password" minlength="6" required><button class="btn primary">Create account</button></form><button class="link" onclick="showUserLogin()">← Back to login</button></div></section></div>`;
}
function register(e){e.preventDefault();let u={id:Date.now(),name:name.value,studentId:studentId.value,phone:phone.value,email:email.value,password:password.value,campus:campus.value,lodge:lodge.value,block:block.value,room:room.value};users.push(u);save();alert('Account created successfully. You can now log in.');showUserLogin();}
function userLogin(e){e.preventDefault();let u=users.find(x=>x.email===email.value&&x.password===password.value);if(!u){alert('Invalid login. Please register first.');return}userDash(u);}
function userDash(u){
app.innerHTML=`<div class="dashboard"><aside class="sidebar"><div class="logo">🛡️ CAMPUS SHIELD</div><nav class="nav"><button class="active">🏠 Dashboard</button><button onclick="reportPage()">🚨 Report Incident</button><button>🔔 Alerts</button><button>📋 My Reports</button><button>👤 Profile</button><button onclick="home()">↪ Logout</button></nav></aside><main class="main"><div class="topbar"><div><h2>Welcome, ${u.name.split(' ')[0]}</h2><p class="muted">Your campus safety dashboard</p></div><div class="profile">👤 ${u.name}</div></div><div class="cards"><div class="card"><small>My Reports</small><strong>${reports.filter(r=>r.userId===u.id).length}</strong></div><div class="card"><small>Active Alerts</small><strong>${reports.filter(r=>r.status!=='Resolved').length}</strong></div><div class="card"><small>Campus</small><strong style="font-size:18px">${u.campus}</strong></div><div class="card"><small>Your Location</small><strong style="font-size:16px">${u.lodge}</strong></div></div><div class="panel"><h3>Quick Report</h3><p class="muted">If you see a security incident, report it immediately.</p><button class="btn danger" onclick="reportPage()">🚨 Report an Incident</button></div><div class="panel"><h3>Recent Reports</h3><div class="report-list">${reports.filter(r=>r.userId===u.id).slice(-5).reverse().map(r=>reportHTML(r)).join('')||'<div class="empty">You have not submitted any reports yet.</div>'}</div></div></main></div>`;
}
function reportHTML(r){return `<div class="report"><div><h4>${r.type}</h4><p>${r.description||'No description provided.'}</p><div class="location">📍 ${r.location}</div></div><span class="badge ${r.status==='Resolved'?'green':'red'}">${r.status}</span></div>`}
function reportPage(){
let u=users[users.length-1];
app.innerHTML=`<div class="auth screen"><section class="brand-panel"><div class="logo">🛡️ CAMPUS SHIELD</div><h1>Report an Incident</h1><p>Keep the report short and clear. Your registered location will be attached to the alert.</p></section><section class="auth-panel"><div class="box"><h2>Emergency Report</h2><p class="muted">Your location: ${u?u.lodge+', '+u.block+', '+u.room:'Not available'}</p><form class="form" onsubmit="submitReport(event)"><label>Incident type</label><select id="type" required><option value="">Select incident</option><option>Suspicious activity</option><option>Theft</option><option>Violence / Threat</option><option>Fire</option><option>Medical emergency</option><option>Other</option></select><label>Description</label><textarea id="description" rows="5" placeholder="Briefly describe what happened..." required></textarea><button class="btn danger">🚨 Send Security Alert</button></form><button class="link" onclick="userDash(u)">← Back to dashboard</button></div></section></div>`;
}
function submitReport(e){e.preventDefault();let u=users[users.length-1];let r={id:Date.now(),userId:u.id,reporter:u.name,type:type.value,description:description.value,location:`${u.campus} — ${u.lodge} — ${u.block} — ${u.room}`,status:'Pending',time:new Date().toLocaleString()};reports.push(r);save();alert('Security alert submitted successfully.');userDash(u);}
function showAdminLogin(){
app.innerHTML=`<div class="auth screen"><section class="brand-panel"><div class="logo">🛡️ CAMPUS SHIELD</div><h1>Security Command Center</h1><p>Authorized personnel can review reports, verify incidents and manage responses.</p></section><section class="auth-panel"><div class="box"><h2>Admin Login</h2><p class="muted">Authorized security personnel only.</p><form class="form" onsubmit="adminLogin(event)"><label>Admin ID</label><input id="adminId" required><label>Password</label><input id="adminPass" type="password" required><button class="btn primary">Enter Dashboard</button></form><p class="muted" style="margin-top:15px;font-size:12px">Demo login: admin / admin123</p><button class="link" onclick="home()">← Back</button></div></section></div>`;
}
function adminLogin(e){e.preventDefault();if(adminId.value==='admin'&&adminPass.value==='admin123')adminDash();else alert('Invalid admin credentials.');}
function adminDash(){
app.innerHTML=`<div class="dashboard"><aside class="sidebar"><div class="logo">🛡️ CAMPUS SHIELD</div><nav class="nav"><button class="active">📊 Dashboard</button><button>🚨 Incidents</button><button>👥 Users</button><button>🗺️ Locations</button><button>📈 Reports</button><button onclick="home()">↪ Logout</button></nav></aside><main class="main"><div class="topbar"><div><h2>Security Command Dashboard</h2><p class="muted">Monitor and respond to campus incidents</p></div><div class="profile">🛡️ Administrator</div></div><div class="cards"><div class="card"><small>Total Incidents</small><strong>${reports.length}</strong></div><div class="card"><small>Pending</small><strong>${reports.filter(r=>r.status==='Pending').length}</strong></div><div class="card"><small>Active</small><strong>${reports.filter(r=>r.status==='Responding').length}</strong></div><div class="card"><small>Resolved</small><strong>${reports.filter(r=>r.status==='Resolved').length}</strong></div></div><div class="panel"><h3>Live Incident Reports</h3><div class="report-list">${reports.slice().reverse().map(r=>`<div class="report"><div><h4>🚨 ${r.type} <span class="badge ${r.status==='Resolved'?'green':'red'}">${r.status}</span></h4><p><b>Reporter:</b> ${r.reporter}</p><p><b>Time:</b> ${r.time}</p><div class="location">📍 ${r.location}</div><p style="margin-top:7px">${r.description}</p></div><div style="display:flex;flex-direction:column;gap:8px;min-width:115px">${r.status!=='Resolved'?`<button class="btn light" onclick="updateStatus(${r.id},'Responding')">Responding</button><button class="btn primary" onclick="updateStatus(${r.id},'Resolved')">Resolve</button>`:'<span class="badge green">Closed</span>'}</div></div>`).join('')||'<div class="empty">No incident reports yet.</div>'}</div></div></main></div>`;
}
function updateStatus(id,status){let r=reports.find(x=>x.id===id);if(r){r.status=status;save();adminDash();}}
home();
